# Data Preprocessing

The objective of this stage is to prepare the dataset for
machine learning.

The preprocessing steps include:

1. Loading the dataset
2. Removing unnecessary variables
3. Separating features and target
4. Encoding categorical variables
5. Splitting the dataset into training and testing sets
6. Preparing the final model-ready dataset

In [7]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/construction_cost_dataset_50_projects.csv"
)

df.head()

,Project_ID,Land_Area_sqft,Total_Floor_Area_sqft,Number_of_Floors,Building_Type,Location,Foundation_Type,Project_Duration_months,Material_Cost_crore_BDT,Labour_Cost_crore_BDT,Total_Cost_crore_BDT
0,1,7038,17800,5,Commercial,Dhaka,Pile,16.7,4.10,1.71,7.44
1,2,2060,4300,4,Residential,Other City,Isolated Footing,8.5,0.88,0.38,1.34
2,3,6627,35900,8,Residential,Dhaka,Isolated Footing,28.5,8.00,2.78,11.92
3,4,4912,14200,5,Commercial,Other City,Raft,18.7,4.02,1.19,6.11
4,5,6322,34500,8,Commercial,Other City,Pile,29.4,7.40,2.52,11.21

In [8]:
X = df.drop(columns=["Total_Cost_crore_BDT"])

y = df["Total_Cost_crore_BDT"]

In [9]:
X.head()

,Project_ID,Land_Area_sqft,Total_Floor_Area_sqft,Number_of_Floors,Building_Type,Location,Foundation_Type,Project_Duration_months,Material_Cost_crore_BDT,Labour_Cost_crore_BDT
0,1,7038,17800,5,Commercial,Dhaka,Pile,16.7,4.10,1.71
1,2,2060,4300,4,Residential,Other City,Isolated Footing,8.5,0.88,0.38
2,3,6627,35900,8,Residential,Dhaka,Isolated Footing,28.5,8.00,2.78
3,4,4912,14200,5,Commercial,Other City,Raft,18.7,4.02,1.19
4,5,6322,34500,8,Commercial,Other City,Pile,29.4,7.40,2.52

In [10]:
y.head()

0     7.44
1     1.34
2    11.92
3     6.11
4    11.21
Name: Total_Cost_crore_BDT, dtype: float64

In [11]:
X.shape

(50, 10)

In [12]:
y.shape

(50,)

In [13]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/construction_cost_dataset_50_projects.csv"
)

df = df.drop(columns=["Project_ID"])

X = df.drop(columns=["Total_Cost_crore_BDT"])

y = df["Total_Cost_crore_BDT"]

X.head()

,Land_Area_sqft,Total_Floor_Area_sqft,Number_of_Floors,Building_Type,Location,Foundation_Type,Project_Duration_months,Material_Cost_crore_BDT,Labour_Cost_crore_BDT
0,7038,17800,5,Commercial,Dhaka,Pile,16.7,4.10,1.71
1,2060,4300,4,Residential,Other City,Isolated Footing,8.5,0.88,0.38
2,6627,35900,8,Residential,Dhaka,Isolated Footing,28.5,8.00,2.78
3,4912,14200,5,Commercial,Other City,Raft,18.7,4.02,1.19
4,6322,34500,8,Commercial,Other City,Pile,29.4,7.40,2.52

In [14]:
X.shape

(50, 9)

In [15]:
y.shape

(50,)

In [16]:
categorical_columns = [
    "Building_Type",
    "Location",
    "Foundation_Type"
]

X[categorical_columns].head()

  Building_Type    Location   Foundation_Type
0    Commercial       Dhaka              Pile
1   Residential  Other City  Isolated Footing
2   Residential       Dhaka  Isolated Footing
3    Commercial  Other City              Raft
4    Commercial  Other City              Pile

In [17]:
X[categorical_columns].nunique()

Building_Type      2
Location           3
Foundation_Type    3
dtype: int64

In [20]:
for col in categorical_columns:
    print(f"\n{col}")
    print(X[col].unique())

Building_Type
<StringArray>
['Commercial', 'Residential']
Length: 2, dtype: str

Location
<StringArray>
['Dhaka', 'Other City', 'Chattogram']
Length: 3, dtype: str

Foundation_Type
<StringArray>
['Pile', 'Isolated Footing', 'Raft']
Length: 3, dtype: str

In [21]:
X_encoded = pd.get_dummies(
    X,
    columns = categorical_columns,
    drop_first = True
)

X_encoded.head()

,Land_Area_sqft,Total_Floor_Area_sqft,Number_of_Floors,Project_Duration_months,Material_Cost_crore_BDT,Labour_Cost_crore_BDT,Building_Type_Residential,Location_Dhaka,Location_Other City,Foundation_Type_Pile,Foundation_Type_Raft
0,7038,17800,5,16.7,4.10,1.71,False,True,False,True,False
1,2060,4300,4,8.5,0.88,0.38,True,False,True,False,False
2,6627,35900,8,28.5,8.00,2.78,True,True,False,False,False
3,4912,14200,5,18.7,4.02,1.19,False,False,True,False,True
4,6322,34500,8,29.4,7.40,2.52,False,False,True,True,False

In [22]:
X_encoded.shape

(50, 11)

In [23]:
X_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Land_Area_sqft             50 non-null     int64
 1   Total_Floor_Area_sqft      50 non-null     int64
 2   Number_of_Floors           50 non-null     int64
 3   Project_Duration_months    50 non-null     float64
 4   Material_Cost_crore_BDT    50 non-null     float64
 5   Labour_Cost_crore_BDT      50 non-null     float64
 6   Building_Type_Residential  50 non-null     bool
 7   Location_Dhaka             50 non-null     bool
 8   Location_Other City        50 non-null     bool
 9   Foundation_Type_Pile       50 non-null     bool
 10  Foundation_Type_Raft       50 non-null     bool
dtypes: bool(5), float64(3), int64(3)
memory usage: 2.7 KB

In [16]:
drop_first=True

In [17]:
X_encoded.dtypes

Land_Area_sqft                 int64
Total_Floor_Area_sqft          int64
Number_of_Floors               int64
Project_Duration_months      float64
Material_Cost_crore_BDT      float64
Labour_Cost_crore_BDT        float64
Building_Type_Residential       bool
Location_Dhaka                  bool
Location_Other City             bool
Foundation_Type_Pile            bool
Foundation_Type_Raft            bool
dtype: object

In [18]:
X_encoded.shape

(50, 11)

In [24]:
#from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.20,
    random_state=42
)

In [22]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (40, 11)
X_test : (10, 11)
y_train: (40,)
y_test : (10,)

In [23]:
categorical_columns = [
    "Building_Type",
    "Location",
    "Foundation_Type"
]

X_encoded = pd.get_dummies(
    X,
    columns=categorical_columns,
    drop_first=True
)

X_encoded.head()

,Land_Area_sqft,Total_Floor_Area_sqft,Number_of_Floors,Project_Duration_months,Material_Cost_crore_BDT,Labour_Cost_crore_BDT,Building_Type_Residential,Location_Dhaka,Location_Other City,Foundation_Type_Pile,Foundation_Type_Raft
0,7038,17800,5,16.7,4.10,1.71,False,True,False,True,False
1,2060,4300,4,8.5,0.88,0.38,True,False,True,False,False
2,6627,35900,8,28.5,8.00,2.78,True,True,False,False,False
3,4912,14200,5,18.7,4.02,1.19,False,False,True,False,True
4,6322,34500,8,29.4,7.40,2.52,False,False,True,True,False

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.20,
    random_state=42
)

In [25]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (40, 11)
X_test : (10, 11)
y_train: (40,)
y_test : (10,)